
import MyContext from "@/Helper/Context"
import './globals.css';

export const metadata = {
  title: 'Mandira',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body suppressHydrationWarning >
      {/*{children} */}
        <MyContext>
          {children}
        </MyContext>          
      </body>
    </html>
  );
}
